version: '3.8'
services:
  postgis:
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgis/postgresql_data:/var/lib/postgresql/data:Z
  geoserver:
    image: terrestris/geoserver:2.19.2
    ports:
      - 8080:8080
    environment:
      EXTRA_JAVA_OPTS: -Xms1g -Xmx2g
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver_data/:Z
      - ./geoserver/additional_libs:/opt/additional_libs/:Z
    depends_on:
      - postgis
  nginx:
    image: nginx:1.19.9-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - geoserver
